export default {
  primary: '#FF9D6C',
  primaryDark: '#E57E4E',
  primaryLight: '#FFBEA0',
  secondary: '#8A6FD6',
  secondaryLight: '#B5A2F3',
  accentGreen: '#7ED9A1',
  accentBlue: '#7ECBFF',
  accentYellow: '#FFDE72',
  accentPink: '#FFABC4',
  bgMain: '#FFF9F5',
  bgCard: '#FFFFFF',
  bgCardHover: '#F8F4FF',
  textPrimary: '#4A4A4A',
  textSecondary: '#6E6E6E',
  textTertiary: '#9E9E9E',
  textLight: '#FFFFFF',
  borderLight: 'rgba(0, 0, 0, 0.1)',
};